# Generated by Django 3.2 on 2023-09-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(default='main/img/news_photos/news_def.jpg', upload_to='main/img/news_photos/'),
        ),
    ]
