# Generated by Django 3.2 on 2023-09-30 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_team_num_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Активно', 'Активно'), ('Архив', 'Архив'), ('регистрация', 'Регистрация')], default='Активно', max_length=20),
        ),
    ]
