# Generated by Django 3.2 on 2023-10-16 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20231001_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='news',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='main.news'),
        ),
    ]
